# Generated by Django 4.0.3 on 2022-03-19 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tab_partido_politico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_partido', models.CharField(max_length=255, verbose_name='Partido')),
                ('str_descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('int_numero_votavel', models.CharField(default='', max_length=255, verbose_name='Numero')),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criação')),
                ('str_sistema', models.CharField(default='', max_length=255, verbose_name='Situação')),
            ],
        ),
        migrations.CreateModel(
            name='Tab_tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coluna01', models.BooleanField(default=True, verbose_name='Como um AS nome BooleanField')),
                ('coluna02', models.IntegerField(default=0, verbose_name='Como um AS nome IntegerField')),
                ('coluna03', models.DecimalField(decimal_places=10, max_digits=11, verbose_name='Como um AS nome DecimalField')),
                ('coluna04', models.CharField(default='', max_length=255, verbose_name='Como um AS nome CharField')),
                ('coluna05', models.TextField(default='', verbose_name='Como um AS nome TextField')),
                ('coluna06', models.ImageField(upload_to='', verbose_name='Como um AS nome ImageField')),
                ('coluna07', models.FloatField(default=0, verbose_name='Como um AS nome FloatField')),
                ('coluna08', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Como um AS nome DateTimeField')),
            ],
        ),
        migrations.CreateModel(
            name='Tab_2020_candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_geracao', models.CharField(default='', max_length=255, verbose_name='Data')),
                ('tm_geracao', models.CharField(default='', max_length=255, verbose_name='Hora')),
                ('int_ano_eleicao', models.CharField(default='', max_length=255, verbose_name='Ano')),
                ('int_tipo_eleicao', models.CharField(default='', max_length=255, verbose_name='TipoN')),
                ('str_tipo_eleicao', models.CharField(default='', max_length=255, verbose_name='TipoC')),
                ('int_turno', models.CharField(default='', max_length=255, verbose_name='Turno')),
                ('int_cod_eleicao', models.CharField(default='', max_length=255, verbose_name='Cod')),
                ('str_eleicao', models.CharField(default='', max_length=255, verbose_name='Eleições')),
                ('dt_eleicao', models.CharField(default='', max_length=255, verbose_name='Data')),
                ('str_tipo_abrangencia', models.CharField(default='', max_length=255, verbose_name='Abrangência')),
                ('str_sigla_uf', models.CharField(default='', max_length=255, verbose_name='UF')),
                ('str_sigla_unidade_eleitoral', models.CharField(default='', max_length=255, verbose_name='Unidade')),
                ('int_cod_cargo', models.CharField(default='', max_length=255, verbose_name='Cod')),
                ('str_desc_cargo', models.CharField(default='', max_length=255, verbose_name='Cargo')),
                ('str_partido_politico', models.CharField(default='', max_length=255, verbose_name='Partido 1')),
                ('int_numero_votavel', models.CharField(default='', max_length=255, verbose_name='Nº')),
                ('str_nome_votavel', models.CharField(default='', max_length=255, verbose_name='Nome')),
                ('str_nome_social', models.CharField(default='', max_length=255, verbose_name='Político')),
                ('str_vice_suplente', models.CharField(default='', max_length=255, verbose_name='Vice')),
                ('int_qtd_votos', models.CharField(default='', max_length=255, verbose_name='Votos')),
                ('str_situacao', models.CharField(default='', max_length=255, verbose_name='Situação')),
                ('str_onde', models.CharField(default='', max_length=255, verbose_name='Onde')),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criação')),
                ('str_sistema', models.CharField(default='', max_length=255, verbose_name='Situação')),
                ('key_partido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apppolitico.tab_partido_politico', verbose_name='Partido 2')),
            ],
        ),
    ]
