# Generated by Django 4.0.3 on 2022-03-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppolitico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='key_partido',
            field=models.ForeignKey(default='00', on_delete=django.db.models.deletion.DO_NOTHING, to='apppolitico.tab_partido_politico', verbose_name='Partido 2'),
        ),
    ]
