# Generated by Django 4.0.3 on 2022-03-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppolitico', '0003_alter_tab_partido_politico_int_numero_votavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_partido_politico',
            name='str_sistema',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Situação'),
        ),
    ]
