# Generated by Django 4.0.3 on 2022-03-19 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apppolitico', '0004_alter_tab_partido_politico_str_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='dt_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='dt_eleicao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='dt_geracao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='int_ano_eleicao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='int_cod_cargo',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Cod'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='int_cod_eleicao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Cod'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='int_numero_votavel',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Nº'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='int_qtd_votos',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Votos'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='int_tipo_eleicao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='TipoN'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='int_turno',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_desc_cargo',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_eleicao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Eleições'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_nome_social',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Político'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_nome_votavel',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_onde',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Onde'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_partido_politico',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Partido 1'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_sigla_uf',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_sigla_unidade_eleitoral',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_sistema',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_situacao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_tipo_abrangencia',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Abrangência'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_tipo_eleicao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='TipoC'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='str_vice_suplente',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Vice'),
        ),
        migrations.AlterField(
            model_name='tab_2020_candidatos',
            name='tm_geracao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='tab_partido_politico',
            name='dt_criacao',
            field=models.DateTimeField(null=django.utils.timezone.now, verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='tab_partido_politico',
            name='int_numero_votavel',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='tab_partido_politico',
            name='str_descricao',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tab_partido_politico',
            name='str_partido',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='tab_partido_politico',
            name='str_sistema',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Situação'),
        ),
    ]
