# Generated by Django 4.0.3 on 2022-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppolitico', '0006_alter_tab_partido_politico_int_numero_votavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_2020_candidatos',
            name='str_nome_unidade_eleitoral',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Unidade'),
        ),
    ]
